name: Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  docs:
    name: Generate docs on OTP ${{ matrix.otp }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        otp: ["24"] # https://www.erlang.org/downloads
        rebar3: ["3.18.0"] # https://www.rebar3.org

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}

      - name: Cache Hex packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-hex-${{ hashFiles('**/rebar.lock') }}
          restore-keys: ${{ runner.os }}-hex-

      - name: Generate docs by ExDoc
        run: rebar3 ex_doc
