name: Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  docs:
    name: Generate docs on OTP ${{ matrix.otp }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        otp: ["24"]
        rebar3: ["3.17.0"]
        elixir: ["1.12"]

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache Hex packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-hex-${{ hashFiles('**/rebar.lock') }}
          restore-keys: ${{ runner.os }}-hex-

      - name: Install ExDoc
        # run: mix escript.install hex ex_doc --force
        # TODO: Temporary solution. See: https://github.com/elixir-lang/ex_doc/issues/1402
        run: mix escript.install github elixir-lang/ex_doc --force

      - name: Generate docs by ExDoc
        run: sh docs.sh $GITHUB_SHA

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: doc
          retention-days: 1
