name: Doc

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

jobs:

  docs:
    name: Build EDoc on OTP ${{ matrix.otp }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        otp: ["24"]
        rebar3: ["3.17.0"]

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ${{ runner.os }}-erlang-${{ matrix.otp }}-${{ hashFiles('**/rebar.lock') }}
          restore-keys: ${{ runner.os }}-erlang-${{ matrix.otp }}-

      - name: Build EDoc
        run: make docs
