name: Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  docs:
    name: Generate docs on OTP ${{ matrix.otp }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        otp: ["24"] # https://www.erlang.org/downloads
        rebar3: ["3.17.0"] # https://www.rebar3.org
        elixir: ["1.12"] # https://github.com/elixir-lang/elixir/releases

    env:
      ex_doc_version: "0.25.5" # https://hex.pm/packages/ex_doc

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache Hex packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-hex-${{ hashFiles('**/rebar.lock') }}
          restore-keys: ${{ runner.os }}-hex-

      - name: Install ExDoc
        run: mix escript.install hex ex_doc ${{ env.ex_doc_version }} --force

      - name: Generate docs by ExDoc
        run: sh docs.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: doc
          retention-days: 1
